version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=data-engineer-cluster.cyhh5bfevlmn.us-east-1.redshift.amazonaws.com
      - DB_PORT=5439
      - DB_NAME=data-engineer-database
      - DB_USER=armandorafaelbohorquez_coderhouse
      - DB_PASSWORD=25eE08PxcY
      - DEBUG=FALSE
